# Generated by Django 5.1.5 on 2025-03-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='choice',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
